[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'sonjapeterson/1989.vim'

[[plugins]]
repo = 'zah/nim.vim'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'rhysd/vim-crystal'

[[plugins]]
repo = 'CORDEA/vim-glue'

[[plugins]]
repo = 'CORDEA/vim-volt'

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
